import { FileText, Maximize2 } from 'lucide-react';
import { ExportActions } from './ExportActions';
import { ReportHeader } from './ReportHeader';
import { ExecutiveSummary } from './ExecutiveSummary';
import { ReportSections } from './ReportSections';
import { ReportSidebar } from './ReportSidebar';
import type { Analysis } from '../types/analysis';

interface ReportPreviewProps {
  analysis: Analysis;
}

export function ReportPreview({ analysis }: ReportPreviewProps) {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <FileText className="h-6 w-6 text-indigo-400" />
          <h2 className="text-2xl font-bold text-white">Report Preview</h2>
        </div>
        <ExportActions jobId={analysis.id} />
      </div>

      <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden shadow-2xl relative">
        {/* Toolbar for the PDF viewer look */}
        <div className="bg-gray-950 border-b border-gray-800 px-4 py-3 flex items-center justify-between">
          <div className="text-xs font-mono text-gray-500 flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-red-500/80"></span>
            <span className="w-3 h-3 rounded-full bg-yellow-500/80"></span>
            <span className="w-3 h-3 rounded-full bg-green-500/80"></span>
            <span className="ml-2">{analysis.repositoryId}-analysis-report.pdf</span>
          </div>
          <button aria-label="Maximize report view" className="text-gray-400 hover:text-white transition-colors">
            <Maximize2 className="h-4 w-4" />
          </button>
        </div>

        {/* The actual "paper" container */}
        <div className="p-8 max-h-[800px] overflow-y-auto bg-gray-900 custom-scrollbar">
          <div className="max-w-5xl mx-auto bg-white dark:bg-[#0a0a0a] rounded-sm shadow-sm overflow-hidden border border-gray-200 dark:border-gray-800 relative min-h-[1056px] text-gray-900 dark:text-gray-100">
            {/* Watermark */}
            <div className="absolute inset-0 pointer-events-none flex items-center justify-center opacity-[0.02] dark:opacity-[0.03] overflow-hidden">
              <span className="text-9xl font-black transform -rotate-45 text-gray-900 dark:text-white whitespace-nowrap">
                DevLens AI
              </span>
            </div>

            <div className="p-8 md:p-12 relative z-10">
              <ReportHeader analysis={analysis} />
              
              <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
                <div className="lg:col-span-3">
                  <div id="executive-summary">
                    <ExecutiveSummary analysis={analysis} />
                  </div>
                  <div id="detailed-findings" className="mt-8">
                    <ReportSections analysis={analysis} />
                  </div>
                </div>
                <div className="lg:col-span-1 border-t lg:border-t-0 lg:border-l border-gray-200 dark:border-gray-800 pt-8 lg:pt-0 lg:pl-8">
                  <ReportSidebar analysis={analysis} />
                </div>
              </div>
              
              <div className="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-500 pb-4">
                Generated by DevLens AI • Confidential & Proprietary • Page 1
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
